/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Fuzzer {
  constructor(coverageMap: Buffer, config?: FuzzerConfig | undefined | null, watchdog?: Watchdog | undefined | null, shmemHandle?: ShmemHandle | undefined | null)
  addSeed(input: Buffer): void
  getNextInput(): Buffer
  reportResult(exitKind: ExitKind, execTimeNs: number): IterationResult
  /**
   * Perform one calibration iteration for the most recently added corpus entry.
   * Returns `true` if more calibration runs are needed.
   */
  calibrateRun(execTimeNs: number): boolean
  /**
   * Finalize calibration for the most recently added corpus entry.
   * Updates per-testcase and global metadata with calibrated values.
   */
  calibrateFinish(): void
  /**
   * Initiate a mutational stage for the most recently calibrated corpus entry.
   *
   * Dispatches to I2S (when CmpLog data is available), Generalization, or Grimoire
   * (when Grimoire is enabled). Returns the first stage-mutated input as a `Buffer`,
   * or `null` if any of the following apply:
   * - A stage is already active
   * - No interesting corpus entry is pending
   * - No applicable stage exists for the entry
   */
  beginStage(): Buffer | null
  /**
   * Process the result of a stage execution and return the next candidate input.
   *
   * Returns the next stage-mutated input as a `Buffer`, or `null` if the stage is
   * complete (iterations exhausted) or no stage is active.
   */
  advanceStage(exitKind: ExitKind, execTimeNs: number): Buffer | null
  /**
   * Cleanly terminate the current stage without evaluating the final execution's
   * coverage. No-op if no stage is active.
   *
   * If the exit kind is Crash or Timeout, the current stage input is recorded
   * as a solution (crash artifact writing is handled by JS, but this ensures
   * `solution_count` and `FuzzerStats` reflect stage-found crashes).
   *
   * Errors if the internal solutions corpus fails to accept the entry.
   */
  abortStage(exitKind: ExitKind): void
  get cmpLogEntryCount(): number
  get stats(): FuzzerStats
  /**
   * Stash the current input to the owned shmem region.
   *
   * Delegates to the owned `ShmemHandle`'s seqlock write protocol.
   * No-op if no `ShmemHandle` was provided at construction.
   *
   * Used by JS-orchestrated paths (calibration, stages, minimization)
   * when the shmem handle is owned by the Fuzzer.
   */
  stashInput(input: Uint8Array): void
  /**
   * Run the target function with optional watchdog protection.
   *
   * If a Watchdog was provided at construction, arms it with `timeoutMs`,
   * calls the target at the NAPI C level with V8 termination handling,
   * disarms, and returns `{ exitKind, error?, result? }`.
   *
   * If no Watchdog was provided, calls the target directly without timeout
   * enforcement and returns the same result shape.
   */
runTarget(target: (data: Buffer) => void | Promise<void>, input: Buffer, timeoutMs: number): { exitKind: number; error?: Error; result?: unknown }
/**
 * Arm the owned watchdog with a timeout in milliseconds.
 *
 * No-op if no Watchdog was provided at construction. Used by the
 * per-iteration fallback path for async targets that need to re-arm
 * the watchdog before awaiting a Promise.
 */
armWatchdog(timeoutMs: number): void
/**
 * Returns `true` if the owned watchdog fired since the last `disarmWatchdog()`.
 *
 * Always returns `false` if no Watchdog was provided at construction.
 * Used by the per-iteration fallback path for async targets to
 * distinguish timeout from crash after awaiting a Promise.
 */
get didWatchdogFire(): boolean
/**
 * Disarm the owned watchdog.
 *
 * No-op if no Watchdog was provided at construction. Used by the
 * per-iteration fallback path for async targets.
 */
disarmWatchdog(): void
/**
 * Disable CmpLog recording and shut down the owned watchdog thread.
 *
 * Disables CmpLog recording so non-deterministic GC of this Fuzzer
 * cannot interfere with a future Fuzzer's CmpLog state. Signals the
 * background watchdog thread to exit, wakes it via condvar, and joins
 * it. No-op for the watchdog if none was provided at construction or
 * if already shut down. Called from the fuzz loop's finally block.
 */
shutdown(): void
/**
 * Run a batch of fuzzing iterations in a tight Rust-internal loop.
 *
 * For each iteration: generate/mutate input, stash to shmem, arm watchdog,
 * call the JS callback, disarm watchdog, evaluate coverage, process CmpLog.
 * Exits early on the first interesting input, solution, or callback error.
 *
 * The callback receives `(inputBuffer, inputLength)` and returns an
 * `ExitKind` number (0=Ok, 1=Crash). Invalid return values are treated
 * as Ok. The callback MUST NOT retain a reference to `inputBuffer`.
 */
runBatch(callback: (inputBuffer: Buffer, inputLength: number) => number, batchSize: number, timeoutMs: number): BatchResult
}

/**
 * NAPI-exposed handle to a shared memory stash.
 *
 * Wraps a cross-process shared memory region used to exchange the
 * current fuzz input between the supervisor parent and the fuzzing child.
 */
export declare class ShmemHandle {
  /**
   * Allocate a new shmem region (parent side).
   *
   * Writes the magic field and exports the shmem identifier to the
   * `VITIATE_SHMEM` environment variable for the child to attach.
   */
  static allocate(maxInputLen: number): ShmemHandle
  /**
   * Attach to an existing shmem region (child side).
   *
   * Reads the `VITIATE_SHMEM` environment variable, attaches to the
   * region, and validates the magic field.
   */
  static attach(): ShmemHandle
  /**
   * Stash the current input to the shmem region.
   *
   * Call this before each fuzz iteration so the parent (or watchdog)
   * can recover the crashing/timing-out input.
   */
  stashInput(input: Uint8Array): void
  /**
   * Read the stashed input from the shmem region.
   *
   * Used by the parent after the child dies to recover the crashing input.
   */
  readStashedInput(): Buffer
  /**
   * Reset the generation counter to zero.
   *
   * Called by the parent supervisor after reading a crash artifact and
   * before respawning the child. Prevents the new child from seeing
   * stale data from the dead child.
   */
  resetGeneration(): void
}

/** NAPI-exposed Watchdog class. */
export declare class Watchdog {
  /**
   * Create a new Watchdog. Spawns the background thread and caches the V8 isolate.
   *
   * - `artifact_prefix`: Prefix for timeout artifact paths (e.g., `./`, `./out/`, `bug-`).
   *   The artifact filename (`timeout-{hash}`) is appended directly to the prefix.
   * - `shmem`: Optional shared memory handle for input capture before `_exit`.
   *   When running under the supervisor, pass the shmem handle so the watchdog
   *   can read the current input from shmem before calling `_exit`. When running
   *   without the supervisor (Vitest integration), pass `null` - the `_exit`
   *   fallback still fires but without writing a timeout artifact.
   */
  constructor(artifactPrefix: string, shmem?: ShmemHandle | undefined | null)
  /**
   * Arm the watchdog with a timeout in milliseconds.
   * Wakes the watchdog thread to start timing.
   */
  arm(timeoutMs: number): void
  /**
   * Disarm the watchdog. Clears the deadline and cancels any pending
   * V8 termination if the watchdog fired.
   */
  disarm(): void
  /** Returns `true` if the watchdog fired since the last `disarm()`. */
  get didFire(): boolean
  /**
   * Deterministically shut down the watchdog thread.
   *
   * Signals the background thread to exit, wakes it via condvar, and joins
   * it. Safe to call multiple times - subsequent calls are no-ops.
   * Also called automatically by `Drop`, but calling explicitly allows JS
   * callers to release the thread without waiting for GC.
   */
  shutdown(): void
  /**
   * Run the target function with watchdog protection.
   *
   * Arms the watchdog, calls the target, and handles V8 termination at the
   * NAPI C level (where `CancelTerminateExecution` can be called before
   * returning to JavaScript). Returns `{ exitKind, error?, result? }`.
   *
   * If the target returns a Promise, it is returned in `result` for the JS
   * caller to await. Async timeout handling relies on the `_exit` fallback
   * or on TerminateExecution firing during active JS in the continuation.
   *
   * Note: Input stashing is the caller's responsibility. The fuzz loop must
   * call `shmemHandle.stashInput(input)` before calling `runTarget()`.
   */
runTarget(target: (data: Buffer) => void | Promise<void>, input: Buffer, timeoutMs: number): { exitKind: number; error?: Error; result?: unknown }
}

/**
 * Result of a batched fuzzing iteration loop.
 *
 * Returned by `Fuzzer.runBatch()`. The batch exits early on the first
 * interesting input, solution, or unrecoverable error.
 */
export interface BatchResult {
  /**
   * Number of iterations completed in this batch (including the triggering
   * iteration, if any).
   */
  executionsCompleted: number
  /** Why the batch ended: `"completed"`, `"interesting"`, `"solution"`, or `"error"`. */
  exitReason: string
  /**
   * Copy of the input that caused early exit. Present when `exitReason`
   * is not `"completed"`.
   */
  triggeringInput?: Buffer
  /**
   * The `ExitKind` that triggered a solution (1=Crash, 2=Timeout).
   * Present only when `exitReason` is `"solution"`.
   */
  solutionExitKind?: number
}

export declare function createCoverageMap(size: number): Buffer

export declare const enum ExitKind {
  Ok = 0,
  Crash = 1,
  Timeout = 2
}

export interface FuzzerConfig {
  maxInputLen?: number
  seed?: number
  /**
   * Grimoire structure-aware fuzzing control.
   * `true` = force enable, `false` = force disable, absent = auto-detect from corpus UTF-8 content.
   */
  grimoire?: boolean
  /**
   * Unicode-aware mutation control.
   * `true` = force enable, `false` = force disable, absent = auto-detect from corpus UTF-8 content.
   */
  unicode?: boolean
  /**
   * REDQUEEN transform-aware mutation control.
   * `true` = force enable, `false` = force disable, absent = auto-detect (inverted: enabled for binary corpus).
   */
  redqueen?: boolean
  /**
   * Absolute path to an AFL/libfuzzer-format dictionary file.
   * If provided, tokens are parsed via `Tokens::from_file()` and seeded
   * into state metadata before any fuzz iterations execute.
   */
  dictionaryPath?: string
  /**
   * Pre-seeded dictionary tokens from active bug detectors.
   * Inserted into `Tokens` state metadata after user dictionary tokens.
   * Exempt from `MAX_DICTIONARY_SIZE` cap; marked as pre-promoted to
   * prevent CmpLog from re-discovering them.
   */
  detectorTokens?: Array<Buffer>
}

export interface FuzzerStats {
  totalExecs: number
  calibrationExecs: number
  corpusSize: number
  solutionCount: number
  coverageEdges: number
  coverageFeatures: number
  execsPerSec: number
}

/**
 * Install the platform-specific exception/crash handler.
 *
 * - **Windows**: Calls `AddVectoredExceptionHandler` to intercept
 *   `EXCEPTION_ACCESS_VIOLATION`, `EXCEPTION_ILLEGAL_INSTRUCTION`,
 *   `EXCEPTION_STACK_OVERFLOW`, and `EXCEPTION_INT_DIVIDE_BY_ZERO`.
 *   The handler writes crash metadata to shmem and a crash artifact to disk,
 *   then returns `EXCEPTION_CONTINUE_SEARCH` to propagate the exception.
 *
 * - **Unix**: No-op. The parent supervisor detects crashes via the child's
 *   exit signal (SIGSEGV, SIGBUS, SIGABRT, etc.) using Node's `child.on('exit')`
 *   signal property.
 *
 * Safe to call multiple times - subsequent calls are no-ops.
 *
 * - `artifact_prefix`: Prefix for crash artifact paths (e.g., `./`, `./out/`, `bug-`).
 *   The artifact filename (`crash-{hash}`) is appended directly to the prefix.
 */
export declare function installExceptionHandler(shmem: ShmemHandle, artifactPrefix: string): void

/**
 * Result of evaluating a single fuzzing iteration.
 *
 * These outcomes are mutually exclusive by design: LibAFL's `StdFuzzer::check_results()`
 * evaluates the objective (crash/timeout) first, and only evaluates coverage feedback if the
 * objective did not fire. An input is classified into exactly one of these categories.
 */
export declare const enum IterationResult {
  /** Input did not trigger new coverage or a crash/timeout. */
  None = 0,
  /** Input discovered new coverage; added to the corpus. */
  Interesting = 1,
  /** Input triggered a crash or timeout; added to the solutions corpus. */
  Solution = 2
}

/**
 * Record comparison operands for the I2S replacement mutator.
 *
 * When a Fuzzer is active (CmpLog enabled), the comparison operands are
 * recorded for use by the I2S replacement mutator. When no Fuzzer is active,
 * this is a no-op. The function never throws - internal errors are silently
 * ignored because the record call precedes the comparison in the IIFE body,
 * and a throw would skip the comparison, changing program control flow.
 *
 * @param operatorId - Numeric operator ID (0=`===`, 1=`!==`, 2=`==`, 3=`!=`, 4=`<`, 5=`>`, 6=`<=`, 7=`>=`)
 */
export declare function traceCmpRecord(left: unknown, right: unknown, cmpId: number, operatorId: number): void

/**
 * Returns `true` if the V8 C++ shim resolved all required symbols at runtime.
 *
 * Under Node.js on platforms where V8 symbols are visible (glibc Linux, macOS,
 * Windows), this should return `true`. Returns `false` under `cargo test` or
 * on platforms where V8 symbols are not in the dynamic symbol table.
 */
export declare function v8ShimAvailable(): boolean

export declare function version(): string

/** Returns the exit code used by the watchdog's `_exit` fallback for timeouts. */
export declare function watchdogExitCode(): number
