packages:
  - vitiate
  - vitiate-core
  - vitiate-engine
  - vitiate-engine/npm/*
  - vitiate-fuzzed-data-provider
  - vitiate-swc-plugin
  - examples/*
  - docs
auditConfig:
  ignoreGhsas:
    - GHSA-rf6f-7fwh-wjgh

onlyBuiltDependencies:
  - "@optique/core"
  - "@optique/run"
  - "@swc/core"
  - esbuild
  - lefthook
  - sharp

overrides:
  flatted@<=3.4.1: ">=3.4.2"
