/**
 * FuzzedDataProvider — structured consumption of fuzzer-generated byte sequences.
 *
 * This implementation is based on the LLVM libFuzzer FuzzedDataProvider design:
 *   https://github.com/llvm-mirror/compiler-rt/blob/master/include/fuzzer/FuzzedDataProvider.h
 *
 * Algorithms and API surface are derived from the jazzer.js FuzzedDataProvider
 * (Copyright 2023 Code Intelligence GmbH, Apache-2.0):
 *   https://github.com/CodeIntelligenceTesting/jazzer.js
 *
 * Key differences from jazzer.js:
 *   - Accepts Uint8Array instead of Buffer (platform-independent)
 *   - Uses DataView instead of Buffer read methods
 *   - consumeBytes/consumeRemainingAsBytes return Uint8Array instead of number[]
 *   - String methods use an options object instead of positional parameters
 *   - Uses standard TypeError/RangeError instead of custom FloatLengthError
 */

/**
 * Printable ASCII lookup table: maps each byte value (0-255) to a
 * printable ASCII character (codepoints 32-126), cycling over the range.
 */
const PRINTABLE_LOOKUP = new Uint8Array(256);
{
  let nextChar = 32;
  for (let i = 0; i < 256; i++) {
    PRINTABLE_LOOKUP[i] = nextChar;
    nextChar++;
    if (nextChar > 126) {
      nextChar = 32;
    }
  }
}

const MAX_FLOAT = 3.4028235e38;

/** Cached TextDecoder instances keyed by encoding name. */
const decoderCache = new Map<string, TextDecoder>();

function getDecoder(encoding: string): TextDecoder {
  // Normalize to lowercase so "UTF-8", "utf-8", and "utf8" share one entry.
  // TextDecoder itself normalizes internally, but the cache key must match.
  const key = encoding.toLowerCase();
  let decoder = decoderCache.get(key);
  if (decoder === undefined) {
    try {
      decoder = new TextDecoder(encoding);
    } catch {
      throw new RangeError(`Unsupported encoding: ${encoding}`);
    }
    decoderCache.set(key, decoder);
  }
  return decoder;
}

export interface StringOptions {
  encoding?: string;
  printable?: boolean;
}

function assertNonNegativeInteger(value: number, name: string): void {
  if (!Number.isInteger(value)) {
    throw new TypeError(`${name} must be an integer`);
  }
  if (value < 0) {
    throw new RangeError(`${name} must be non-negative`);
  }
}

/**
 * Helper class for reading primitive types from fuzzer-generated byte sequences.
 *
 * Uses the LLVM split-buffer consumption strategy: individual scalar values are
 * consumed from the end (little-endian), bulk data from the front (big-endian).
 */
export class FuzzedDataProvider {
  private readonly data: Uint8Array;
  private readonly view: DataView;
  private frontPointer: number;
  private endPointer: number;

  constructor(data: Uint8Array) {
    this.data = data;
    this.view = new DataView(data.buffer, data.byteOffset, data.byteLength);
    this.frontPointer = 0;
    this.endPointer = data.length;
  }

  get remainingBytes(): number {
    return this.endPointer - this.frontPointer;
  }

  // --- Internal helpers ---

  /**
   * Consume up to `count` bytes from the end of the buffer.
   * Returns the number of bytes actually consumed.
   */
  private consumeFromEnd(count: number): number {
    const actual = Math.min(count, this.remainingBytes);
    this.endPointer -= actual;
    return actual;
  }

  /**
   * Consume up to `count` bytes from the front of the buffer.
   * Returns the number of bytes actually consumed.
   */
  private consumeFromFront(count: number): number {
    const actual = Math.min(count, this.remainingBytes);
    this.frontPointer += actual;
    return actual;
  }

  /**
   * Read an unsigned integer of `numBytes` bytes in little-endian order
   * from the end of the buffer.
   *
   * Precondition: numBytes <= 6 (callers must enforce this to stay within
   * Number.MAX_SAFE_INTEGER). All public entry points enforce this via
   * consumeIntegral's maxNumBytes check or consumeIntegralInRangeInternal's
   * range cap at 2^48-1.
   */
  private readUintLE(numBytes: number): number {
    const consumed = this.consumeFromEnd(numBytes);
    if (consumed === 0) return 0;
    let result = 0;
    for (let i = 0; i < consumed; i++) {
      result += this.data[this.endPointer + i]! * 2 ** (8 * i);
    }
    return result;
  }

  /**
   * Read an unsigned integer of `numBytes` bytes in big-endian order
   * from the front of the buffer.
   */
  private readUintBE(numBytes: number): number {
    const start = this.frontPointer;
    const consumed = this.consumeFromFront(numBytes);
    if (consumed === 0) return 0;
    let result = 0;
    for (let i = 0; i < consumed; i++) {
      result = result * 256 + this.data[start + i]!;
    }
    return result;
  }

  /**
   * Core integral-in-range implementation shared by LE (end) and BE (front) paths.
   */
  private consumeIntegralInRangeInternal(
    min: number,
    max: number,
    fromEnd: boolean,
  ): number {
    if (min === max) return min;
    if (min > max)
      throw new RangeError("min must be less than or equal to max");
    if (this.remainingBytes === 0) return min;

    const range = max - min;
    if (range > 2 ** 48 - 1) {
      throw new RangeError(
        "range exceeds 2^48 - 1: use consumeBigIntegralInRange instead",
      );
    }

    const numBytesToRepresentRange = Math.ceil(Math.log2(range + 1) / 8);
    const numBytesToConsume = Math.min(
      this.remainingBytes,
      numBytesToRepresentRange,
    );

    let rawValue: number;
    if (fromEnd) {
      rawValue = this.readUintLE(numBytesToConsume);
    } else {
      rawValue = this.readUintBE(numBytesToConsume);
    }

    return min + (rawValue % (range + 1));
  }

  /**
   * Core bigint-in-range implementation shared by LE (end) and BE (front) paths.
   */
  private consumeBigIntegralInRangeInternal(
    min: bigint,
    max: bigint,
    fromEnd: boolean,
  ): bigint {
    if (min === max) return min;
    if (min > max)
      throw new RangeError("min must be less than or equal to max");

    const range = max - min;
    let result = 0n;
    let offset = 0n;

    while (range >> offset > 0n && this.remainingBytes > 0) {
      let nextByte: number;
      if (fromEnd) {
        this.endPointer--;
        nextByte = this.data[this.endPointer]!;
        // LE accumulation from end (consistent with consumeIntegral's LE read)
        result |= BigInt(nextByte) << offset;
      } else {
        nextByte = this.data[this.frontPointer]!;
        this.frontPointer++;
        // BE accumulation from front (consistent with consumeIntegrals' BE read)
        result = (result << 8n) | BigInt(nextByte);
      }
      offset += 8n;
    }

    return (result % (range + 1n)) + min;
  }

  // --- Boolean ---

  consumeBoolean(): boolean {
    return (this.consumeIntegral(1) & 1) === 1;
  }

  // --- Integer (number) ---

  consumeIntegral(maxNumBytes: number, isSigned = false): number {
    assertNonNegativeInteger(maxNumBytes, "maxNumBytes");
    if (maxNumBytes < 1 || maxNumBytes > 6) {
      throw new RangeError(
        "maxNumBytes must be between 1 and 6: use consumeBigIntegral for larger values",
      );
    }
    const min = isSigned ? -(2 ** (8 * maxNumBytes - 1)) : 0;
    const max = isSigned
      ? 2 ** (8 * maxNumBytes - 1) - 1
      : 2 ** (8 * maxNumBytes) - 1;
    return this.consumeIntegralInRangeInternal(min, max, true);
  }

  consumeIntegralInRange(min: number, max: number): number {
    return this.consumeIntegralInRangeInternal(min, max, true);
  }

  // --- BigInt ---

  consumeBigIntegral(maxNumBytes: number, isSigned = false): bigint {
    assertNonNegativeInteger(maxNumBytes, "maxNumBytes");
    if (maxNumBytes < 1) {
      throw new RangeError("maxNumBytes must be at least 1");
    }
    let min: bigint;
    let max: bigint;
    if (isSigned) {
      min = -(1n << BigInt(maxNumBytes * 8 - 1));
      max = (1n << BigInt(maxNumBytes * 8 - 1)) - 1n;
    } else {
      min = 0n;
      max = (1n << BigInt(maxNumBytes * 8)) - 1n;
    }
    return this.consumeBigIntegralInRangeInternal(min, max, true);
  }

  consumeBigIntegralInRange(min: bigint, max: bigint): bigint {
    return this.consumeBigIntegralInRangeInternal(min, max, true);
  }

  // --- Floating point ---

  consumeProbabilityFloat(): number {
    return this.consumeIntegral(4) / 0xffffffff;
  }

  consumeProbabilityDouble(): number {
    const n = this.consumeBigIntegral(8, false);
    const d = 0xffffffffffffffffn;
    return Math.min(1.0, Number(n) / Number(d));
  }

  consumeNumber(): number {
    if (this.remainingBytes === 0) return 0;

    if (this.remainingBytes < 8) {
      // Copy remaining bytes into high (most significant) positions of an
      // 8-byte LE buffer, matching LLVM's approach: preserves sign, exponent,
      // and high mantissa bits from the available data.
      const buf = new ArrayBuffer(8);
      const bytes = new Uint8Array(buf);
      const remaining = this.remainingBytes;
      const offset = 8 - remaining;
      for (let i = 0; i < remaining; i++) {
        bytes[offset + i] = this.data[this.endPointer - remaining + i]!;
      }
      this.endPointer -= remaining;
      return new DataView(buf).getFloat64(0, true);
    }

    this.endPointer -= 8;
    return this.view.getFloat64(this.endPointer, true);
  }

  consumeFloat(): number {
    return this.consumeFloatInRange(-MAX_FLOAT, MAX_FLOAT);
  }

  consumeFloatInRange(min: number, max: number): number {
    if (min === max) return min;
    if (min > max)
      throw new RangeError("min must be less than or equal to max");
    if (!Number.isFinite(min) || !Number.isFinite(max))
      throw new RangeError("min and max must be finite");

    let range: number;
    let result = min;

    if (min < 0.0 && max > 0.0 && max > min + MAX_FLOAT) {
      range = max / 2.0 - min / 2.0;
      if (this.consumeBoolean()) {
        result += range;
      }
    } else {
      range = max - min;
    }

    // Clamp to max to guard against floating-point arithmetic overshoot
    // when probability is very close to 1.0 and range is large.
    return Math.min(max, result + range * this.consumeProbabilityFloat());
  }

  consumeDouble(): number {
    return this.consumeDoubleInRange(-Number.MAX_VALUE, Number.MAX_VALUE);
  }

  consumeDoubleInRange(min: number, max: number): number {
    if (min === max) return min;
    if (min > max)
      throw new RangeError("min must be less than or equal to max");
    if (!Number.isFinite(min) || !Number.isFinite(max))
      throw new RangeError("min and max must be finite");

    let range: number;
    let result = min;

    if (min < 0.0 && max > 0.0 && max > min + Number.MAX_VALUE) {
      range = max / 2.0 - min / 2.0;
      if (this.consumeBoolean()) {
        result += range;
      }
    } else {
      range = max - min;
    }

    // Clamp to max to guard against floating-point arithmetic overshoot
    // when probability is very close to 1.0 and range is large.
    return Math.min(max, result + range * this.consumeProbabilityDouble());
  }

  consumeNumberInRange(min: number, max: number): number {
    return this.consumeDoubleInRange(min, max);
  }

  // --- Array consumption (front / big-endian) ---

  private computeArrayLength(
    maxLength: number,
    numBytesPerElement: number,
  ): number {
    const numAvailableBytes = Math.min(
      this.remainingBytes,
      maxLength * numBytesPerElement,
    );
    return Math.ceil(numAvailableBytes / numBytesPerElement);
  }

  consumeBooleans(maxLength: number): boolean[] {
    assertNonNegativeInteger(maxLength, "maxLength");
    const arrayLength = Math.min(this.remainingBytes, maxLength);
    const result = new Array<boolean>(arrayLength);
    for (let i = 0; i < arrayLength; i++) {
      result[i] = (this.data[this.frontPointer + i]! & 1) === 1;
    }
    this.frontPointer += arrayLength;
    return result;
  }

  consumeIntegrals(
    maxLength: number,
    numBytesPerIntegral: number,
    isSigned = false,
  ): number[] {
    assertNonNegativeInteger(maxLength, "maxLength");
    assertNonNegativeInteger(numBytesPerIntegral, "numBytesPerIntegral");
    if (numBytesPerIntegral < 1 || numBytesPerIntegral > 6) {
      throw new RangeError(
        "numBytesPerIntegral must be between 1 and 6: use consumeBigIntegrals for larger values",
      );
    }
    const arrayLength = this.computeArrayLength(maxLength, numBytesPerIntegral);
    const min = isSigned ? -(2 ** (8 * numBytesPerIntegral - 1)) : 0;
    const max = isSigned
      ? 2 ** (8 * numBytesPerIntegral - 1) - 1
      : 2 ** (8 * numBytesPerIntegral) - 1;
    const result = new Array<number>(arrayLength);
    for (let i = 0; i < arrayLength; i++) {
      result[i] = this.consumeIntegralInRangeInternal(min, max, false);
    }
    return result;
  }

  consumeBigIntegrals(
    maxLength: number,
    numBytesPerIntegral: number,
    isSigned = false,
  ): bigint[] {
    assertNonNegativeInteger(maxLength, "maxLength");
    assertNonNegativeInteger(numBytesPerIntegral, "numBytesPerIntegral");
    if (numBytesPerIntegral < 1) {
      throw new RangeError("numBytesPerIntegral must be at least 1");
    }
    const arrayLength = this.computeArrayLength(maxLength, numBytesPerIntegral);
    let min: bigint;
    let max: bigint;
    if (isSigned) {
      min = -(1n << BigInt(numBytesPerIntegral * 8 - 1));
      max = (1n << BigInt(numBytesPerIntegral * 8 - 1)) - 1n;
    } else {
      min = 0n;
      max = (1n << BigInt(numBytesPerIntegral * 8)) - 1n;
    }
    const result = new Array<bigint>(arrayLength);
    for (let i = 0; i < arrayLength; i++) {
      result[i] = this.consumeBigIntegralInRangeInternal(min, max, false);
    }
    return result;
  }

  consumeNumbers(maxLength: number): number[] {
    assertNonNegativeInteger(maxLength, "maxLength");
    const arrayLength = this.computeArrayLength(maxLength, 8);
    const result = new Array<number>(arrayLength);
    for (let i = 0; i < arrayLength; i++) {
      result[i] = this.consumeNumberBE();
    }
    return result;
  }

  private consumeNumberBE(): number {
    if (this.remainingBytes === 0) return 0;

    if (this.remainingBytes < 8) {
      // Copy remaining bytes into high positions of an 8-byte BE buffer
      const buf = new ArrayBuffer(8);
      const bytes = new Uint8Array(buf);
      const remaining = this.remainingBytes;
      for (let i = 0; i < remaining; i++) {
        bytes[i] = this.data[this.frontPointer + i]!;
      }
      this.frontPointer += remaining;
      return new DataView(buf).getFloat64(0, false);
    }

    const result = this.view.getFloat64(this.frontPointer, false);
    this.frontPointer += 8;
    return result;
  }

  consumeBytes(maxLength: number): Uint8Array {
    assertNonNegativeInteger(maxLength, "maxLength");
    const arrayLength = Math.min(this.remainingBytes, maxLength);
    const result = this.data.slice(
      this.frontPointer,
      this.frontPointer + arrayLength,
    );
    this.frontPointer += arrayLength;
    return result;
  }

  consumeRemainingAsBytes(): Uint8Array {
    return this.consumeBytes(this.remainingBytes);
  }

  // --- String consumption ---

  consumeString(maxLength: number, options?: StringOptions): string {
    assertNonNegativeInteger(maxLength, "maxLength");

    const encoding = options?.encoding ?? "utf-8";
    const printable = options?.printable ?? false;

    const arrayLength = Math.min(maxLength, this.remainingBytes);

    const decoder = getDecoder(encoding);

    let bytes: Uint8Array;
    if (printable) {
      bytes = new Uint8Array(arrayLength);
      for (let i = 0; i < arrayLength; i++) {
        bytes[i] = PRINTABLE_LOOKUP[this.data[this.frontPointer + i]!]!;
      }
    } else {
      bytes = this.data.subarray(
        this.frontPointer,
        this.frontPointer + arrayLength,
      );
    }

    this.frontPointer += arrayLength;
    return decoder.decode(bytes);
  }

  consumeRemainingAsString(options?: StringOptions): string {
    return this.consumeString(this.remainingBytes, options);
  }

  consumeStringArray(
    maxArrayLength: number,
    maxStringLength: number,
    options?: StringOptions,
  ): string[] {
    assertNonNegativeInteger(maxArrayLength, "maxArrayLength");
    assertNonNegativeInteger(maxStringLength, "maxStringLength");

    const result: string[] = [];
    while (result.length < maxArrayLength && this.remainingBytes > 0) {
      const before = this.remainingBytes;
      const str = this.consumeString(maxStringLength, options);
      // Guard against zero-byte consumption (e.g. maxStringLength === 0)
      if (this.remainingBytes === before) break;
      result.push(str);
    }
    return result;
  }

  // --- Element picking ---

  pickValue<T>(array: ReadonlyArray<T>): T {
    if (array.length === 0) throw new RangeError("array must not be empty");
    return array[this.consumeIntegralInRange(0, array.length - 1)]!;
  }

  pickValues<T>(array: ReadonlyArray<T>, numValues: number): T[] {
    if (array.length === 0) throw new RangeError("array must not be empty");
    assertNonNegativeInteger(numValues, "numValues");
    if (numValues > array.length) {
      throw new RangeError(
        "numValues must not be greater than the array length",
      );
    }

    const result = new Array<T>(numValues);
    const remaining = array.slice();
    for (let i = 0; i < numValues; i++) {
      const index = this.consumeIntegralInRange(0, remaining.length - 1);
      result[i] = remaining[index]!;
      remaining.splice(index, 1);
    }
    return result;
  }
}
