/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Fuzzer {
  constructor(coverageMap: Buffer, config?: FuzzerConfig | undefined | null)
  addSeed(input: Buffer): void
  getNextInput(): Buffer
  reportResult(exitKind: ExitKind): IterationResult
  get cmpLogEntryCount(): number
  get stats(): FuzzerStats
}

/** NAPI-exposed Watchdog class. */
export declare class Watchdog {
  /**
   * Create a new Watchdog. Spawns the background thread and caches the V8 isolate.
   *
   * - `max_input_len`: Maximum input size for the pre-stash buffer.
   * - `artifact_dir`: Directory to write timeout artifacts.
   */
  constructor(maxInputLen: number, artifactDir: string)
  /**
   * Arm the watchdog with a timeout in milliseconds.
   * Wakes the watchdog thread to start timing.
   */
  arm(timeoutMs: number): void
  /**
   * Disarm the watchdog. Clears the deadline and cancels any pending
   * V8 termination if the watchdog fired.
   */
  disarm(): void
  /**
   * Stash the current input for capture before `_exit`.
   * Call this before each fuzz iteration.
   */
  stashInput(input: Uint8Array): void
  /** Returns `true` if the watchdog fired since the last `disarm()`. */
  get didFire(): boolean
  /**
   * Deterministically shut down the watchdog thread.
   *
   * Signals the background thread to exit, wakes it via condvar, and joins
   * it. Safe to call multiple times — subsequent calls are no-ops.
   * Also called automatically by `Drop`, but calling explicitly allows JS
   * callers to release the thread without waiting for GC.
   */
  shutdown(): void
  /**
   * Run the target function with watchdog protection.
   *
   * Arms the watchdog, calls the target, and handles V8 termination at the
   * NAPI C level (where `CancelTerminateExecution` can be called before
   * returning to JavaScript). Returns `{ exitKind, error?, result? }`.
   *
   * If the target returns a Promise, it is returned in `result` for the JS
   * caller to await. Async timeout handling relies on the `_exit` fallback
   * or on TerminateExecution firing during active JS in the continuation.
   */
runTarget(target: (data: Buffer) => void | Promise<void>, input: Buffer, timeoutMs: number): { exitKind: number; error?: Error; result?: unknown }
}

export declare function createCoverageMap(size: number): Buffer

export declare const enum ExitKind {
  Ok = 0,
  Crash = 1,
  Timeout = 2
}

export interface FuzzerConfig {
  maxInputLen?: number
  seed?: number
}

export interface FuzzerStats {
  totalExecs: number
  corpusSize: number
  solutionCount: number
  coverageEdges: number
  execsPerSec: number
}

/**
 * Result of evaluating a single fuzzing iteration.
 *
 * These outcomes are mutually exclusive by design: LibAFL's `StdFuzzer::check_results()`
 * evaluates the objective (crash/timeout) first, and only evaluates coverage feedback if the
 * objective did not fire. An input is classified into exactly one of these categories.
 */
export declare const enum IterationResult {
  /** Input did not trigger new coverage or a crash/timeout. */
  None = 0,
  /** Input discovered new coverage; added to the corpus. */
  Interesting = 1,
  /** Input triggered a crash or timeout; added to the solutions corpus. */
  Solution = 2
}

/**
 * Perform a JS comparison and return the boolean result.
 *
 * When a Fuzzer is active (CmpLog enabled), the comparison operands are
 * recorded for use by the I2S replacement mutator. When no Fuzzer is active,
 * this is a pure passthrough with no side effects beyond the comparison.
 */
export declare function traceCmp(left: unknown, right: unknown, cmpId: number, op: string): boolean

export declare function version(): string
