/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Fuzzer {
  constructor(coverageMap: Buffer, config?: FuzzerConfig | undefined | null)
  addSeed(input: Buffer): void
  getNextInput(): Buffer
  reportResult(exitKind: ExitKind): IterationResult
  get cmpLogEntryCount(): number
  get stats(): FuzzerStats
}

/**
 * NAPI-exposed handle to a shared memory stash.
 *
 * Wraps a cross-process shared memory region used to exchange the
 * current fuzz input between the supervisor parent and the fuzzing child.
 */
export declare class ShmemHandle {
  /**
   * Allocate a new shmem region (parent side).
   *
   * Writes the magic field and exports the shmem identifier to the
   * `VITIATE_SHMEM` environment variable for the child to attach.
   */
  static allocate(maxInputLen: number): ShmemHandle
  /**
   * Attach to an existing shmem region (child side).
   *
   * Reads the `VITIATE_SHMEM` environment variable, attaches to the
   * region, and validates the magic field.
   */
  static attach(): ShmemHandle
  /**
   * Stash the current input to the shmem region.
   *
   * Call this before each fuzz iteration so the parent (or watchdog)
   * can recover the crashing/timing-out input.
   */
  stashInput(input: Uint8Array): void
  /**
   * Read the stashed input from the shmem region.
   *
   * Used by the parent after the child dies to recover the crashing input.
   */
  readStashedInput(): Buffer
  /**
   * Reset the generation counter to zero.
   *
   * Called by the parent supervisor after reading a crash artifact and
   * before respawning the child. Prevents the new child from seeing
   * stale data from the dead child.
   */
  resetGeneration(): void
}

/** NAPI-exposed Watchdog class. */
export declare class Watchdog {
  /**
   * Create a new Watchdog. Spawns the background thread and caches the V8 isolate.
   *
   * - `artifact_dir`: Directory to write timeout artifacts.
   * - `shmem`: Optional shared memory handle for input capture before `_exit`.
   *   When running under the supervisor, pass the shmem handle so the watchdog
   *   can read the current input from shmem before calling `_exit`. When running
   *   without the supervisor (Vitest integration), pass `null` — the `_exit`
   *   fallback still fires but without writing a timeout artifact.
   */
  constructor(artifactDir: string, shmem?: ShmemHandle | undefined | null)
  /**
   * Arm the watchdog with a timeout in milliseconds.
   * Wakes the watchdog thread to start timing.
   */
  arm(timeoutMs: number): void
  /**
   * Disarm the watchdog. Clears the deadline and cancels any pending
   * V8 termination if the watchdog fired.
   */
  disarm(): void
  /** Returns `true` if the watchdog fired since the last `disarm()`. */
  get didFire(): boolean
  /**
   * Deterministically shut down the watchdog thread.
   *
   * Signals the background thread to exit, wakes it via condvar, and joins
   * it. Safe to call multiple times — subsequent calls are no-ops.
   * Also called automatically by `Drop`, but calling explicitly allows JS
   * callers to release the thread without waiting for GC.
   */
  shutdown(): void
  /**
   * Run the target function with watchdog protection.
   *
   * Arms the watchdog, calls the target, and handles V8 termination at the
   * NAPI C level (where `CancelTerminateExecution` can be called before
   * returning to JavaScript). Returns `{ exitKind, error?, result? }`.
   *
   * If the target returns a Promise, it is returned in `result` for the JS
   * caller to await. Async timeout handling relies on the `_exit` fallback
   * or on TerminateExecution firing during active JS in the continuation.
   *
   * Note: Input stashing is the caller's responsibility. The fuzz loop must
   * call `shmemHandle.stashInput(input)` before calling `runTarget()`.
   */
runTarget(target: (data: Buffer) => void | Promise<void>, input: Buffer, timeoutMs: number): { exitKind: number; error?: Error; result?: unknown }
}

export declare function createCoverageMap(size: number): Buffer

export declare const enum ExitKind {
  Ok = 0,
  Crash = 1,
  Timeout = 2
}

export interface FuzzerConfig {
  maxInputLen?: number
  seed?: number
}

export interface FuzzerStats {
  totalExecs: number
  corpusSize: number
  solutionCount: number
  coverageEdges: number
  execsPerSec: number
}

/**
 * Install the platform-specific exception/crash handler.
 *
 * - **Windows**: Calls `AddVectoredExceptionHandler` to intercept
 *   `EXCEPTION_ACCESS_VIOLATION`, `EXCEPTION_ILLEGAL_INSTRUCTION`,
 *   `EXCEPTION_STACK_OVERFLOW`, and `EXCEPTION_INT_DIVIDE_BY_ZERO`.
 *   The handler writes crash metadata to shmem and a crash artifact to disk,
 *   then returns `EXCEPTION_CONTINUE_SEARCH` to propagate the exception.
 *
 * - **Unix**: No-op. The parent supervisor detects crashes via the child's
 *   exit signal (SIGSEGV, SIGBUS, SIGABRT, etc.) using Node's `child.on('exit')`
 *   signal property.
 *
 * Safe to call multiple times — subsequent calls are no-ops.
 */
export declare function installExceptionHandler(shmem: ShmemHandle, artifactDir: string): void

/**
 * Result of evaluating a single fuzzing iteration.
 *
 * These outcomes are mutually exclusive by design: LibAFL's `StdFuzzer::check_results()`
 * evaluates the objective (crash/timeout) first, and only evaluates coverage feedback if the
 * objective did not fire. An input is classified into exactly one of these categories.
 */
export declare const enum IterationResult {
  /** Input did not trigger new coverage or a crash/timeout. */
  None = 0,
  /** Input discovered new coverage; added to the corpus. */
  Interesting = 1,
  /** Input triggered a crash or timeout; added to the solutions corpus. */
  Solution = 2
}

/**
 * Perform a JS comparison and return the boolean result.
 *
 * When a Fuzzer is active (CmpLog enabled), the comparison operands are
 * recorded for use by the I2S replacement mutator. When no Fuzzer is active,
 * this is a pure passthrough with no side effects beyond the comparison.
 */
export declare function traceCmp(left: unknown, right: unknown, cmpId: number, op: string): boolean

export declare function version(): string
