/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Fuzzer {
  constructor(coverageMap: Buffer, config?: FuzzerConfig | undefined | null)
  addSeed(input: Buffer): void
  getNextInput(): Buffer
  reportResult(exitKind: ExitKind): IterationResult
  get stats(): FuzzerStats
}

export declare function createCoverageMap(size: number): Buffer

export declare const enum ExitKind {
  Ok = 0,
  Crash = 1,
  Timeout = 2
}

export interface FuzzerConfig {
  maxInputLen?: number
  seed?: number
}

export interface FuzzerStats {
  totalExecs: number
  corpusSize: number
  solutionCount: number
  coverageEdges: number
  execsPerSec: number
}

/**
 * Result of evaluating a single fuzzing iteration.
 *
 * These outcomes are mutually exclusive by design: LibAFL's `StdFuzzer::check_results()`
 * evaluates the objective (crash/timeout) first, and only evaluates coverage feedback if the
 * objective did not fire. An input is classified into exactly one of these categories.
 */
export declare const enum IterationResult {
  /** Input did not trigger new coverage or a crash/timeout. */
  None = 0,
  /** Input discovered new coverage; added to the corpus. */
  Interesting = 1,
  /** Input triggered a crash or timeout; added to the solutions corpus. */
  Solution = 2
}

/**
 * Perform a JS comparison and return the boolean result.
 *
 * This is a passthrough stub: it evaluates the comparison correctly but does
 * not feed operand values to LibAFL for value-profile feedback. When CmpLog
 * integration lands, the function body changes but the signature stays the same.
 */
export declare function traceCmp(left: unknown, right: unknown, cmpId: number, op: string): boolean

export declare function version(): string
